name: swiftride
description: A ride-hailing app built with Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  # Location services (if you want to get user's current location)
  location: ^5.0.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  provider: ^6.1.1
  # Permissions handling
  permission_handler: ^11.0.0
  
  # For search functionality (optional - for geocoding addresses)
  geocoding: ^2.1.1
   # For smooth animations
  animations: ^2.0.8
  lottie: ^3.3.1
  country_picker: ^2.0.27 
  image_picker: ^1.1.2
  intl: ^0.20.2
  file_picker: ^10.3.3
  logger: ^2.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
  
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
